FROM golang:1.25-alpine AS builder

WORKDIR /workspace

COPY . .

RUN CGO_ENABLED=0 GOOS=linux \
    go build -ldflags="-w -s" -o /server ./services/vendor

FROM alpine:3.21

RUN apk add --no-cache ca-certificates tzdata

COPY --from=builder /server /server

EXPOSE 8081

CMD ["/server"]
