events {
    worker_connections 1024;
}

http {
    upstream user_service {
        server user-service:8080;
    }

    upstream vendor_service {
        server vendor-service:8080;
    }

    upstream search_service {
        server search-service:8080;
    }

    server {
        listen 80;

        proxy_connect_timeout 2s;
        proxy_send_timeout    5s;
        proxy_read_timeout    5s;

        location /user/ {
            proxy_pass         http://user_service/;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        location /vendor/ {
            proxy_pass         http://vendor_service/;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_read_timeout 11s;
            proxy_send_timeout 11s;
        }

        location /search/ {
            proxy_pass         http://search_service/;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
    }
}
