name: Deploy User Functions

on:
  workflow_call:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      follow:                 ${{ steps.filter.outputs.follow }}
      unfollow:               ${{ steps.filter.outputs.unfollow }}
      

    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            follow:
              - 'users/follows/follow-business/**'
            unfollow:
              - 'users/follows/unfollow-business/**'
            
  follow:
    needs: detect-changes
    if: needs.detect-changes.outputs.follow == 'true'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-function.yml
    with:
      function-name: user-follow
      working-directory: users/follows/follow-business
      gcp_region: ${{ vars.GCP_REGION }}
    secrets: inherit

  unfollow:
    needs: detect-changes
    if: needs.detect-changes.outputs.unfollow == 'true'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-function.yml
    with:
      function-name: user-unfollow
      working-directory: users/follows/unfollow-business
      gcp_region: ${{ vars.GCP_REGION }}
    secrets: inherit