name: Multiple Go Functions Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'register/**'
 
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      register: ${{ steps.filter.outputs.register }}

    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            # register:
            #   - 'register/**'
              
  # deploy-register:
  #   needs: detect-changes
  #   if: needs.detect-changes.outputs.register == 'true'
  #   permissions:
  #     id-token: write
  #     contents: read
  #   uses: ./.github/workflows/deploy-function.yml
  #   with:
  #     working-directory: register
  #     gcp_region: ${{ vars.GCP_REGION }}
  #   secrets: inherit
