name: Multiple Go Functions Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'register/**'
 
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      business-register: ${{ steps.filter.outputs.business-register }}
      business-login: ${{ steps.filter.outputs.business-login }}
      user-login: ${{ steps.filter.outputs.user-login }}
      user-register: ${{ steps.filter.outputs.user-register }}

    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            business-register:
              - 'auth/business/register/**'
            business-login:
              - 'auth/business/login/**'
            user-login:
              - auth/user/login/**'
            user-register:
              - auth/user/register/**'

  business-register:
    needs: detect-changes
    if: needs.detect-changes.outputs.business-register == 'true'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-function.yml
    with:
      working-directory: register
      gcp_region: ${{ vars.GCP_REGION }}
    secrets: inherit

  business-login:
    needs: detect-changes
    if: needs.detect-changes.outputs.business-login == 'true'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-function.yml
    with:
      working-directory: register
      gcp_region: ${{ vars.GCP_REGION }}
    secrets: inherit

  user-login:
    needs: detect-changes
    if: needs.detect-changes.outputs.business-login == 'true'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-function.yml
    with:
      working-directory: register
      gcp_region: ${{ vars.GCP_REGION }}
    secrets: inherit

  user-register:
    needs: detect-changes
    if: needs.detect-changes.outputs.business-login == 'true'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-function.yml
    with:
      working-directory: register
      gcp_region: ${{ vars.GCP_REGION }}
    secrets: inherit