name: Multiple Go Functions Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'auth/business/register/**'
      - 'auth/business/login/**'
      - 'auth/user/login/**'
      - 'auth/user/register/**'
      - 'bridge-service/follow/**'
      - 'bridge-service/like/**'
      - 'bridge-service/push_notification/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      business-register: ${{ steps.filter.outputs.business-register }}
      business-login: ${{ steps.filter.outputs.business-login }}
      user-login: ${{ steps.filter.outputs.user-login }}
      user-register: ${{ steps.filter.outputs.user-register }}

      bridge-service-follow: ${{ steps.filter.outputs.bridge-service-follow }}
      bridge-service-like: ${{ steps.filter.outputs.bridge-service-follow }}
      bridge-service-push-notification: ${{ steps.filter.outputs.bridge-service-follow }}

      business-categories-add: ${{ steps.filter.outputs.business-categories-add }}
      business-categories-get: ${{ steps.filter.outputs.business-categories-get }}

    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            business-register:
              - 'auth/business/register/**'
            business-login:
              - 'auth/business/login/**'
            user-login:
              - 'auth/user/login/**'      
            user-register:
              - 'auth/user/register/**'  

            bridge-service-follow:
              - 'bridge-service/follow/**'
            bridge-service-like:
              - 'bridge-service/like/**'
            bridge-service-push-notification:
              - 'bridge-service/push_notification'

            business-categories-add:
              - 'business/categories/add_categories/**'
            business-categories-get:
              - 'business/categories/get_categories/**'

  business-register:
    needs: detect-changes
    if: needs.detect-changes.outputs.business-register == 'true'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-function.yml
    with:
      working-directory: auth/business/register
      gcp_region: ${{ vars.GCP_REGION }}
    secrets: inherit

  business-login:
    needs: detect-changes
    if: needs.detect-changes.outputs.business-login == 'true'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-function.yml
    with:
      working-directory: auth/business/login
      gcp_region: ${{ vars.GCP_REGION }}
    secrets: inherit

  user-login:
    needs: detect-changes
    if: needs.detect-changes.outputs.user-login == 'true'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-function.yml
    with:
      working-directory: auth/user/login
      gcp_region: ${{ vars.GCP_REGION }}
    secrets: inherit

  user-register:
    needs: detect-changes
    if: needs.detect-changes.outputs.user-register == 'true'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-function.yml
    with:
      working-directory: auth/user/register
      gcp_region: ${{ vars.GCP_REGION }}
    secrets: inherit

  bridge-service-follow:
    needs: detect-changes
    if: needs.detect-changes.outputs.bridge-service-follow
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-function.yml
    with:
      working-directory: bridge-service/follow
      gcp_region: ${{ vars.GCP_REGION }}
    secrets: inherit

  bridge-service-like:
    needs: detect-changes
    if: needs.detect-changes.outputs.bridge-service-like
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-function.yml
    with:
      working-directory: bridge-service/like
      gcp_region: ${{ vars.GCP_REGION }}
    secrets: inherit

  bridge-service-push-notification:
    needs: detect-changes
    if: needs.detect-changes.outputs.bridge-service-push-notification
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-function.yml
    with:
      working-directory: bridge-service/push_notification
      gcp_region: ${{ vars.GCP_REGION }}
    secrets: inherit

  business-categories-add:
    needs: detect-changes
    if: needs.detect-changes.outputs.business-categories-add
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-function.yml
    with:
      working-directory: business/categories/add_categories
      gcp_region: ${{ vars.GCP_REGION }}
    secrets: inherit

  business-categories-get:
    needs: detect-changes
    if: needs.detect-changes.outputs.business-categories-get
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-function.yml
    with:
      working-directory: business/categories/get_categories
      gcp_region: ${{ vars.GCP_REGION }}
    secrets: inherit
  