name: Server Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  changes:
    runs-on: self-hosted

    outputs:
      user: ${{ steps.filter.outputs.user }}
      search: ${{ steps.filter.outputs.search }}
      vendor: ${{ steps.filter.outputs.vendor }}
      gateway: ${{ steps.filter.outputs.gateway }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            user:
              - 'app/**'
            search:
              - 'services/search/**'
            vendor:
              - 'services/vendor/**'
            gateway:
              - 'gateway/**'

  deploy-user:
    if: needs.changes.outputs.user == 'true'
    needs: changes
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -f app/Dockerfile -t spotnearr_user:latest ./app

      - name: Deploy user service
        working-directory: app
        env:
          TF_PLUGIN_CACHE_DIR: $HOME/.terraform.d/plugin-cache
          TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
          TF_VAR_captcha_secret_key: ${{ secrets.CAPTCHA_SECRET_KEY }}
          TF_VAR_postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
          TF_VAR_rabbitmq_password: ${{ secrets.RABBITMQ_PASSWORD }}
        run: |
          mkdir -p $TF_PLUGIN_CACHE_DIR
          terraform init \
            -backend-config="path=../../states/user/terraform.tfstate"
          terraform apply -auto-approve

  deploy-vendor:
    if: needs.changes.outputs.vendor == 'true'
    needs: changes
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploy vendor service"

  deploy-search:
    if: needs.changes.outputs.search == 'true'
    needs: changes
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploy search service"

  deploy-gateway:
    if: needs.changes.outputs.gateway == 'true'
    needs: changes
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploy gateway"
