name: Server Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  changes:
    runs-on: self-hosted

    outputs:
      user: ${{ steps.filter.outputs.user }}
      search: ${{ steps.filter.outputs.search }}
      vendor: ${{ steps.filter.outputs.vendor }}
      gateway: ${{ steps.filter.outputs.gateway }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            user:
              - 'user/**'

            search:
              - 'search/**'

            vendor:
              - 'vendor/**'

            gateway:
              - 'gateway/**'


  deploy-gateway:
        if: needs.changes.output.gateway == 'true'
        needs: changes

        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v4
        - run: echo "Deploy gateway"


  deploy-user:
        if: needs.changes.outputs.user == 'true'
        needs: changes

        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v4
        - run: echo "Deploy user service"

  deploy-vendor:
        if: needs.changes.outputs.vendor == 'true'
        needs: changes

        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v4
        - run: echo "Deploy vendor service"

  deploy-search:
        if: needs.changes.outputs.search == 'true'
        needs: changes

        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v4
        - run: echo "Deploy search service"